name: Upload File from SharePoint

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Choose configuration'
        required: true
        default: 'legacy'
        options:
          - legacy
          - new
      sharepoint_link:
        description: 'SharePoint file link'
        required: true
        default: 'https://ejgroup.sharepoint.com/:x:/r/sites/EJPeakTeamSite/_layouts/15/Doc.aspx?sourcedoc=%7B68C5977C-D50E-43A6-89EE-56E068695575%7D&file=6951-035-05%20training%20-%20RTU%20Change%20Request%20QC%20Checklist%20V1.0.xlsm&action=default&mobileredirect=true'

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set configuration
      run: echo "Config selected: ${{ github.event.inputs.config }}"

    - name: Download file from SharePoint
      env:
        SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
        SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
      run: |
        curl -L -o sharepoint_file.xlsm --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" "${{ github.event.inputs.sharepoint_link }}"

    - name: Create uploads directory if it doesn't exist
      run: mkdir -p uploads

    - name: Move file to uploads directory
      run: mv sharepoint_file.xlsm uploads/

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add uploads/sharepoint_file.xlsm
        git commit -m 'Add file from SharePoint to uploads folder'
        git push
