
name: Upload File

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file to upload'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload file
      run: |
        echo "Uploading file from path: ${{ github.event.inputs.file_path }}"
        mkdir -p upload
        cp ${{ github.event.inputs.file_path }} upload/
      env:
        FILE_PATH: ${{ github.event.inputs.file_path }}

    - name: Archive and upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: uploaded-file
        path: upload/
